### ISSUE TITLE
Hi pscott! Please read this since I don't know how to contact you!

### ISSUE THREAD

**Issue by DonFinidi** [pscott/override#1]
Hi @pscott!,

I just checked that you approved a Pull Request for app-ethereum.

Problem is that I have another merge pending ( https://github.com/LedgerHQ/app-ethereum/pull/208) and I don't know how to get it approved or at least reviewed.

Any help from your side would be highly appreciated!

I'm so sorry for reaching you over here but I was unable to find any other way.

Thank you very much sir!,
DonFinidi

**Comment by pscott** [comment]
Hi @DonFinidi
Indeed, weird way of getting in contact with me, but I feel you!

Here's a link to the ledger dev slack: https://developers.ledger.com/contact/

I'm closing this issue, but please come and say hi :)
